"""change first_name to display_name

Revision ID: ad59210acf2a
Revises: dffd9d7db92a
Create Date: 2025-03-31 23:05:22.158280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad59210acf2a'
down_revision = 'dffd9d7db92a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=50), nullable=False))
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
